// Package rules keeps herma's generated Claude Code rules files: the project file inside a checkout and the global file under ~/.claude. It owns only .claude/rules/herma and never writes through a symlink.
package rules

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

// Path is the principles file relative to the checkout root.
const Path = ".claude/rules/herma/principles.md"

// GlobalPath is the global principles file relative to the home directory.
// Claude Code loads ~/.claude/rules in every project.
const GlobalPath = ".claude/rules/herma/global-principles.md"

// Header is the first bytes of every principles file herma generates. Sync
// replaces or removes only a regular file that starts with it.
const Header = "<!-- Generated by herma from accepted principles."

// ErrUnsafePath reports an existing path component that is not a real
// directory or regular file, such as a symlink planted by a cloned repository.
var ErrUnsafePath = errors.New("refusing to write through a symlink or non-directory")

var dirs = []string{".claude", filepath.Join(".claude", "rules"), filepath.Join(".claude", "rules", "herma")}

// Sync makes the checkout's principles file hold content (see syncFile).
func Sync(checkout string, content []byte) (bool, error) {
	return syncFile(checkout, "principles.md", true, content)
}

// SyncGlobal makes ~/.claude/rules/herma/global-principles.md hold content. It
// does nothing when home has no .claude folder, since Claude Code is absent.
func SyncGlobal(home string, content []byte) (bool, error) {
	info, err := os.Lstat(filepath.Join(home, ".claude"))
	if errors.Is(err, fs.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if !info.IsDir() {
		return false, fmt.Errorf("%w: %s", ErrUnsafePath, filepath.Join(home, ".claude"))
	}
	return syncFile(home, "global-principles.md", false, content)
}

// syncFile makes .claude/rules/herma/<name> under rootDir hold content and
// reports whether it changed. It creates the directories and, when gitignore
// is set, a .gitignore containing "*" (never editing an existing one, and
// refusing one that is not a regular file ignoring everything); it removes the
// file when content is empty, and replaces or removes only a file herma
// generated.
func syncFile(rootDir, name string, gitignore bool, content []byte) (bool, error) {
	root, err := os.OpenRoot(rootDir)
	if err != nil {
		return false, err
	}
	defer func() { _ = root.Close() }()
	hermaDir := dirs[len(dirs)-1]
	file := filepath.Join(hermaDir, name)
	if len(content) == 0 {
		present, err := existingDirs(root)
		if err != nil || !present {
			return false, err
		}
		current, err := readGenerated(root, file)
		if err != nil || current == nil {
			return false, err
		}
		return true, root.Remove(file)
	}
	if err := makeDirs(root); err != nil {
		return false, err
	}
	if gitignore {
		if err := ensureGitignore(root, filepath.Join(hermaDir, ".gitignore")); err != nil {
			return false, err
		}
	}
	current, err := readGenerated(root, file)
	if err != nil {
		return false, err
	}
	if bytes.Equal(current, content) {
		return false, nil
	}
	return true, replace(root, hermaDir, file, content)
}

func existingDirs(root *os.Root) (bool, error) {
	for _, dir := range dirs {
		info, err := root.Lstat(dir)
		if errors.Is(err, fs.ErrNotExist) {
			return false, nil
		}
		if err != nil {
			return false, err
		}
		if !info.IsDir() {
			return false, fmt.Errorf("%w: %s", ErrUnsafePath, dir)
		}
	}
	return true, nil
}

func makeDirs(root *os.Root) error {
	for _, dir := range dirs {
		if err := root.Mkdir(dir, 0o755); err != nil && !errors.Is(err, fs.ErrExist) {
			return err
		}
		info, err := root.Lstat(dir)
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return fmt.Errorf("%w: %s", ErrUnsafePath, dir)
		}
	}
	return nil
}

func ensureGitignore(root *os.Root, path string) error {
	f, err := root.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if errors.Is(err, fs.ErrExist) {
		return checkGitignore(root, path)
	}
	if err != nil {
		return err
	}
	_, err = f.WriteString("*\n")
	if cerr := f.Close(); err == nil {
		err = cerr
	}
	return err
}

// checkGitignore accepts an existing .gitignore only if it is a regular file
// that ignores everything, so a planted one cannot get principles.md committed.
func checkGitignore(root *os.Root, path string) error {
	info, err := root.Lstat(path)
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%w: %s", ErrUnsafePath, path)
	}
	data, err := root.ReadFile(path)
	if err != nil {
		return err
	}
	if string(bytes.TrimSpace(data)) != "*" {
		return fmt.Errorf("%w: %s", ErrUnsafePath, path)
	}
	return nil
}

// readGenerated returns the existing file's content, or nil when it is absent.
// Anything herma did not generate — a symlink, a directory, another file type, or
// a regular file without Header — is refused and left untouched.
func readGenerated(root *os.Root, path string) ([]byte, error) {
	info, err := root.Lstat(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	if !info.Mode().IsRegular() {
		return nil, fmt.Errorf("%w: %s", ErrUnsafePath, path)
	}
	data, err := root.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if !bytes.HasPrefix(data, []byte(Header)) {
		return nil, fmt.Errorf("%w: %s", ErrUnsafePath, path)
	}
	return data, nil
}

func replace(root *os.Root, dir, path string, content []byte) error {
	var entropy [8]byte
	if _, err := rand.Read(entropy[:]); err != nil {
		return err
	}
	tmp := filepath.Join(dir, ".principles-"+hex.EncodeToString(entropy[:])+".tmp")
	f, err := root.OpenFile(tmp, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return err
	}
	_, err = f.Write(content)
	if cerr := f.Close(); err == nil {
		err = cerr
	}
	if err == nil {
		err = root.Rename(tmp, path)
	}
	if err != nil {
		_ = root.Remove(tmp)
	}
	return err
}
