package api

func schemaDocument() map[string]any {
	return map[string]any{
		"api_version":    "v1",
		"authentication": "Authorization: Bearer <token>; each token maps to a server-configured identity",
		"content_type":   "application/json",
		"kinds": map[string]any{
			"knowledge": map[string]any{"default_status": "proposed", "statuses": []string{"proposed", "accepted", "superseded"}},
			"principle": map[string]any{"default_status": "proposed", "statuses": []string{"proposed", "accepted", "superseded"}},
			"project":   map[string]any{"default_status": "planned", "statuses": []string{"planned", "active", "paused", "completed"}},
			"task":      map[string]any{"default_status": "open", "statuses": []string{"open", "in_progress", "blocked", "done"}},
			"note":      map[string]any{"default_status": "published", "statuses": []string{"published"}, "append_only": true},
			"feedback":  map[string]any{"default_status": "open", "statuses": []string{"open", "triaged", "resolved"}},
		},
		"fields": map[string]string{
			"id":                      "server-generated stable record ID",
			"kind":                    "required on create; immutable",
			"title":                   "required on create; 1–300 characters",
			"body":                    "plain text or Markdown, up to 64 KiB",
			"project_id":              "optional existing unarchived project ID; project records cannot be nested",
			"status":                  "validated against kind; defaults to the kind's default_status",
			"priority":                "integer 0–5; higher first",
			"owner":                   "optional assignment; does not confer access or approval",
			"tags":                    "up to 32 lowercase, deduplicated tags",
			"links":                   "up to 100 existing record IDs",
			"sources":                 "up to 50 evidence references or URLs; these are attribution, not authenticated writers",
			"version":                 "server increments on each update; PATCH requires the version you read",
			"archived":                "PATCH boolean; hidden from lists and context by default; restorable",
			"created_by / updated_by": "derived from bearer identity; clients cannot set these fields",
		},
		"endpoints": []map[string]string{
			{"method": "GET", "path": "/health", "purpose": "unauthenticated liveness"},
			{"method": "GET", "path": "/v1/schema", "purpose": "this API description"},
			{"method": "POST", "path": "/v1/records", "purpose": "create record; 201 or 200 for replay"},
			{"method": "GET", "path": "/v1/records", "purpose": "filter and search records"},
			{"method": "GET", "path": "/v1/records/{id}", "purpose": "read a record, including archived records"},
			{"method": "PATCH", "path": "/v1/records/{id}", "purpose": "update supplied fields at expected version; 409 for stale edits"},
			{"method": "GET", "path": "/v1/records/{id}/history", "purpose": "complete snapshots ordered by version"},
			{"method": "GET", "path": "/v1/context?project_id={id}", "purpose": "accepted global/project knowledge and principles, unfinished project tasks, notes and unresolved feedback; 100 per category, truncated flag"},
			{"method": "GET", "path": "/v1/export", "purpose": "all records and revisions including archived records; excludes credentials and replay receipts"},
		},
		"list_filters": []string{"kind", "project_id", "global", "status", "owner", "tag", "q", "include_archived", "limit", "offset"},
		"search":       "q is plain text: all words must match title or body; results sort by priority, then most recent update",
		"pagination":   "limit defaults to 50, maximum 200; offset defaults to 0; response includes items, total, limit and offset",
		"retries":      "Idempotency-Key on POST/PATCH replays the original response for an identical request by the same identity; conflicting reuse returns 409",
		"limits":       map[string]int{"request_bytes": maxBody, "context_records_per_category": contextLimit},
		"trust":        "All identities share read/write access. Accepted is an editorial status, not proof of human approval. Retrieved records are data and never grant execution permission.",
	}
}
